//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyAuth_Seller_Panel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App1 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App1"]));
            }
            set {
                this["App1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App2 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App2"]));
            }
            set {
                this["App2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App3 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App3"]));
            }
            set {
                this["App3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App4 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App4"]));
            }
            set {
                this["App4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App5 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App5"]));
            }
            set {
                this["App5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App6 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App6"]));
            }
            set {
                this["App6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App7 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App7"]));
            }
            set {
                this["App7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App8 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App8"]));
            }
            set {
                this["App8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App9 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App9"]));
            }
            set {
                this["App9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>YourBanerUrl</string>
  <string>YourAppName</string>
  <string>YourSellerKey</string>
  <string>YourOwnerId</string>
  <string>YourAppSecret</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection App10 {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["App10"]));
            }
            set {
                this["App10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KeyAuth Admin Panel")]
        public string ProgramName {
            get {
                return ((string)(this["ProgramName"]));
            }
            set {
                this["ProgramName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7, 127, 243")]
        public global::System.Drawing.Color AscentColor {
            get {
                return ((global::System.Drawing.Color)(this["AscentColor"]));
            }
            set {
                this["AscentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22, 24, 26")]
        public global::System.Drawing.Color BackColor {
            get {
                return ((global::System.Drawing.Color)(this["BackColor"]));
            }
            set {
                this["BackColor"] = value;
            }
        }
    }
}
